/** Shared mutable runtime for EGE prep modules. */
export const E = {
  STORAGE_KEY: "ege-prep.scores.v1",
  LISTENING_TARGET_GAPS: 15,
  prepNextPulseTimers: {},
  toastTimer: null,
  taskDigitBuffer: { taskId: "", digits: "", timer: null },
  mcKeyboardState: { taskId: "", questionIndex: -1 },
  listeningNavAlignRaf: 0,
  topicNavAlignRaf: 0,
  topicNavResizeObserver: null,
  speakingTimerHandles: {},
  speakingTimerControllers: {},
  speakingAskCycles: {},
  examTimerInterval: null,
  state: {
    topic: null,
    topicId: "",
    sectionMeta: null,
    playlist: false,
    playlistWasComplete: false,
    examEndsAt: 0,
    examMinutes: 0,
    examTimerKey: "",
    scores: {},
    placementFinalized: false,
    examPhase: "",
    examReviewing: false,
    writing38Choice: "",
    writing38Drafts: {},
    speakingTimerTouched: {},
    activeTaskId: null,
    listeningSelections: {},
    listeningRuns: {},
    listeningSteps: {},
    prepLayouts: {},
  },
};
